// <auto-generated />
namespace Online_Food_Order_Software.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class feed_promo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(feed_promo));
        
        string IMigrationMetadata.Id
        {
            get { return "202102271008083_feed_promo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
