// <auto-generated />
namespace Online_Food_Order_Software.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class feed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(feed));
        
        string IMigrationMetadata.Id
        {
            get { return "202102271058004_feed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
