// <auto-generated />
namespace Online_Food_Order_Software.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class signupcurrections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(signupcurrections));
        
        string IMigrationMetadata.Id
        {
            get { return "202112140339067_signupcurrections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
